
package calculator;

public class CalculadoraBasica2 extends javax.swing.JFrame {

    String valor1;
    String valor2;
    String operacion;
    
    public CalculadoraBasica2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtPantalla = new javax.swing.JTextArea();
        ResPantalla = new javax.swing.JTextField();
        Boton7 = new javax.swing.JButton();
        Boton4 = new javax.swing.JButton();
        Boton1 = new javax.swing.JButton();
        Boton8 = new javax.swing.JButton();
        Boton5 = new javax.swing.JButton();
        BotonBorrarDigito = new javax.swing.JButton();
        BotonRestar = new javax.swing.JButton();
        Boton9 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();
        Boton6 = new javax.swing.JButton();
        Boton3 = new javax.swing.JButton();
        BotonSumar = new javax.swing.JButton();
        BotonBorrarNumero = new javax.swing.JButton();
        BotonMultiplicar = new javax.swing.JButton();
        BotonInvertir = new javax.swing.JButton();
        BotonCambiarSigno = new javax.swing.JButton();
        BotonDecimal = new javax.swing.JButton();
        BotonDividir = new javax.swing.JButton();
        BotonIgual = new javax.swing.JButton();
        Boton0 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtPantalla.setColumns(20);
        TxtPantalla.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TxtPantalla.setRows(5);
        jScrollPane1.setViewportView(TxtPantalla);

        ResPantalla.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ResPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResPantallaActionPerformed(evt);
            }
        });

        Boton7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton7.setText("7");
        Boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton7ActionPerformed(evt);
            }
        });

        Boton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton4.setText("4");
        Boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton4ActionPerformed(evt);
            }
        });

        Boton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton1.setText("1");
        Boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton1ActionPerformed(evt);
            }
        });

        Boton8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton8.setText("8");
        Boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton8ActionPerformed(evt);
            }
        });

        Boton5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton5.setText("5");
        Boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton5ActionPerformed(evt);
            }
        });

        BotonBorrarDigito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        BotonBorrarDigito.setText("C");
        BotonBorrarDigito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarDigitoActionPerformed(evt);
            }
        });

        BotonRestar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonRestar.setText("-");
        BotonRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRestarActionPerformed(evt);
            }
        });

        Boton9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton9.setText("9");
        Boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton9ActionPerformed(evt);
            }
        });

        Boton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton2.setText("2");
        Boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton2ActionPerformed(evt);
            }
        });

        Boton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton6.setText("6");
        Boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton6ActionPerformed(evt);
            }
        });

        Boton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton3.setText("3");
        Boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton3ActionPerformed(evt);
            }
        });

        BotonSumar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonSumar.setText("+");
        BotonSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSumarActionPerformed(evt);
            }
        });

        BotonBorrarNumero.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        BotonBorrarNumero.setText("CE");
        BotonBorrarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarNumeroActionPerformed(evt);
            }
        });

        BotonMultiplicar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonMultiplicar.setText("x");
        BotonMultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMultiplicarActionPerformed(evt);
            }
        });

        BotonInvertir.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        BotonInvertir.setText("1/X");
        BotonInvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInvertirActionPerformed(evt);
            }
        });

        BotonCambiarSigno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonCambiarSigno.setText("±");
        BotonCambiarSigno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonCambiarSignoActionPerformed(evt);
            }
        });

        BotonDecimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonDecimal.setText(".");
        BotonDecimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDecimalActionPerformed(evt);
            }
        });

        BotonDividir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonDividir.setText("÷");
        BotonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonDividirActionPerformed(evt);
            }
        });

        BotonIgual.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BotonIgual.setText("=");
        BotonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonIgualActionPerformed(evt);
            }
        });

        Boton0.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Boton0.setText("0");
        Boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonCambiarSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BotonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BotonInvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BotonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BotonBorrarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BotonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BotonBorrarDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ResPantalla)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ResPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBorrarDigito, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonBorrarNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonMultiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonInvertir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonCambiarSigno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonDecimal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDividirActionPerformed
        if(valor1 == null){
            valor1 = ResPantalla.getText();
            operacion = ":";
        }else if(valor2 == null){
            valor2 = ResPantalla.getText();
            double resultado = calcular(operacion, valor1, valor2);
            operacion = ":";
            valor1 = Double.toString(resultado);
            valor2 = null;
        }
        TxtPantalla.setText(TxtPantalla.getText()+operacion);
        ResPantalla.setText("");
    }//GEN-LAST:event_BotonDividirActionPerformed

    private void BotonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonIgualActionPerformed

        valor2 = ResPantalla.getText();
        double resultado = calcular(operacion, valor1, valor2);
        ResPantalla.setText(Double.toString(resultado));
        TxtPantalla.setText("");
        valor1 = null;
        valor2 = null;
    }//GEN-LAST:event_BotonIgualActionPerformed

    private void ResPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResPantallaActionPerformed

    private void Boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton7ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"7");
        TxtPantalla.setText(TxtPantalla.getText()+"7");
    }//GEN-LAST:event_Boton7ActionPerformed

    private void Boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton8ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"8");
        TxtPantalla.setText(TxtPantalla.getText()+"8");
    }//GEN-LAST:event_Boton8ActionPerformed

    private void Boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton9ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"9");
        TxtPantalla.setText(TxtPantalla.getText()+"9");
    }//GEN-LAST:event_Boton9ActionPerformed

    private void Boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton4ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"4");
        TxtPantalla.setText(TxtPantalla.getText()+"4");
    }//GEN-LAST:event_Boton4ActionPerformed

    private void Boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton5ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"5");
        TxtPantalla.setText(TxtPantalla.getText()+"5");
    }//GEN-LAST:event_Boton5ActionPerformed

    private void Boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton6ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"6");
        TxtPantalla.setText(TxtPantalla.getText()+"6");
    }//GEN-LAST:event_Boton6ActionPerformed

    private void Boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton1ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"1");
        TxtPantalla.setText(TxtPantalla.getText()+"1");
    }//GEN-LAST:event_Boton1ActionPerformed

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"2");
        TxtPantalla.setText(TxtPantalla.getText()+"2");
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton3ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"3");
        TxtPantalla.setText(TxtPantalla.getText()+"3");
    }//GEN-LAST:event_Boton3ActionPerformed

    private void Boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton0ActionPerformed
        ResPantalla.setText(ResPantalla.getText()+"0");
        TxtPantalla.setText(TxtPantalla.getText()+"0");
    }//GEN-LAST:event_Boton0ActionPerformed

    private void BotonCambiarSignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonCambiarSignoActionPerformed
        if(!ResPantalla.getText().equals("")){
            if(esNumNegativo(ResPantalla.getText())){
                ResPantalla.setText(ResPantalla.getText().substring(1));
            }else{
                ResPantalla.setText("-"+ResPantalla.getText());
            }
        }else{
            ResPantalla.setText("-");
        }
    }//GEN-LAST:event_BotonCambiarSignoActionPerformed

    private void BotonDecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonDecimalActionPerformed
        if(ResPantalla.getText().length()<=0 || ResPantalla.getText().equals("-")){
            ResPantalla.setText(ResPantalla.getText()+"0.");
        }else if(!existePunto(ResPantalla.getText())){
            ResPantalla.setText(ResPantalla.getText()+".");
        }
    }//GEN-LAST:event_BotonDecimalActionPerformed

    private void BotonRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRestarActionPerformed
        if(valor1 == null){
            valor1 = ResPantalla.getText();
            operacion = "-";
        }else if(valor2 == null){
            valor2 = ResPantalla.getText();
            double resultado = calcular(operacion, valor1, valor2);
            operacion = "-";
            valor1 = Double.toString(resultado);
            valor2 = null;
        }
        TxtPantalla.setText(TxtPantalla.getText()+operacion);
        ResPantalla.setText("");
    }//GEN-LAST:event_BotonRestarActionPerformed

    private void BotonSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSumarActionPerformed
        if(valor1 == null){
            valor1 = ResPantalla.getText();
            operacion = "+";
        }else if(valor2 == null){
            valor2 = ResPantalla.getText();
            double resultado = calcular(operacion, valor1, valor2);
            operacion = "+";
            valor1 = Double.toString(resultado);
            valor2 = null;
        }
        TxtPantalla.setText(TxtPantalla.getText()+operacion);
        ResPantalla.setText("");
    }//GEN-LAST:event_BotonSumarActionPerformed

    private void BotonMultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMultiplicarActionPerformed
        if(valor1 == null){
            valor1 = ResPantalla.getText();
            operacion = "x";
        }else if(valor2 == null){
            valor2 = ResPantalla.getText();
            double resultado = calcular(operacion, valor1, valor2);
            operacion = "x";
            valor1 = Double.toString(resultado);
            valor2 = null;
        }
        TxtPantalla.setText(TxtPantalla.getText()+operacion);
        ResPantalla.setText("");
    }//GEN-LAST:event_BotonMultiplicarActionPerformed

    private void BotonBorrarDigitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarDigitoActionPerformed
        TxtPantalla.setText("");
        ResPantalla.setText("");
        valor1 = null;
        valor2 = null;
    }//GEN-LAST:event_BotonBorrarDigitoActionPerformed

    private void BotonBorrarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarNumeroActionPerformed
        int i = ResPantalla.getText().length();
        int j = TxtPantalla.getText().length();
        TxtPantalla.setText(TxtPantalla.getText().substring(0, (j-i)));
        ResPantalla.setText("");
    }//GEN-LAST:event_BotonBorrarNumeroActionPerformed

    private void BotonInvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInvertirActionPerformed
        double numero = Double.parseDouble(ResPantalla.getText());
        double inverso = 1/numero;
        ResPantalla.setText(Double.toString(inverso));
        
    }//GEN-LAST:event_BotonInvertirActionPerformed
   
    public static boolean existePunto(String cadena){
        boolean resultado = false;
        for(int i=0; i<cadena.length(); i++){
            if(cadena.charAt(i) == '.'){
                resultado = true;
            }
        }
        return resultado;
    }

    public static boolean esNumNegativo(String cadena){
        boolean esNegativo = false;
        if(cadena.charAt(0) == '-'){
            esNegativo = true;
        }
        return esNegativo;
    }
    
    public static double calcular(String signo, String num1, String num2){
        double resultado = 0;
            switch(signo){
                case "+":
                    resultado = Double.valueOf(num1) + Double.valueOf(num2);
                    break;
                case "-":
                    resultado = Double.valueOf(num1) - Double.valueOf(num2);
                    break;
                case "x":
                    resultado = Double.valueOf(num1) * Double.valueOf(num2);
                    break;
                case ":":
                    resultado = Double.valueOf(num1) / Double.valueOf(num2);
            }
        return resultado;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraBasica2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraBasica2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton0;
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    private javax.swing.JButton Boton3;
    private javax.swing.JButton Boton4;
    private javax.swing.JButton Boton5;
    private javax.swing.JButton Boton6;
    private javax.swing.JButton Boton7;
    private javax.swing.JButton Boton8;
    private javax.swing.JButton Boton9;
    private javax.swing.JButton BotonBorrarDigito;
    private javax.swing.JButton BotonBorrarNumero;
    private javax.swing.JButton BotonCambiarSigno;
    private javax.swing.JButton BotonDecimal;
    private javax.swing.JButton BotonDividir;
    private javax.swing.JButton BotonIgual;
    private javax.swing.JButton BotonInvertir;
    private javax.swing.JButton BotonMultiplicar;
    private javax.swing.JButton BotonRestar;
    private javax.swing.JButton BotonSumar;
    private javax.swing.JTextField ResPantalla;
    private javax.swing.JTextArea TxtPantalla;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
